### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by ethanfrey** [irisnet/irisnet-crypto#49]
There is no LICENSE file in the repo.

The only hint is in `package.json`, which is the default of `ISC`, but it is nice to be explicit about the licensing requirements of an open-source package, so I know the restrictions upon importing it in another project.

**Comment by zhiqiang-bianjie** [comment]
Thank you for your reminder, I will add LICENSE soon.

**Comment by ethanfrey** [comment]
Thank you. Just saw the Apache 2.0 license. Very nice choice 👍
